server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://coms-4156.cjpbkidulxni.us-east-1.rds.amazonaws.com
    username: admin
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: humanlearningrentermatch
  expiration: 2592000000 # 30days*24h*60min*60s*1000ms
